name: ChemName2CID

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: running ChemName2CID

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: running chemname2cid
      run: |
         git config --global user.email "ucecwme@ucl.ac.uk"
         git config --global user.name "nickcafferry"
         git init
         echo "Initializing the program....................."
         
         echo "---------------------------------------------"
         cd ../
         mkdir output
         echo "output file already created!"
         
         echo "---------------------------------------------"
         cd Fechii-Application-Chemical-Engineer/
         cd doc/
         python3.6 ChemName2CID.py
         cd ChemName2CID/
         ls -lt

         echo "recording information already unpacked!"
         echo "Show the path of this file: "
         pwd
         echo "---------------------------------------------"
         
         echo "transporting new outputs to artifacts..."
         cp ChemNametoCID.txt /home/runner/work/Fechii-Application-Chemical-Engineer/output/
                
         cd /home/runner/work/Fechii-Application-Chemical-Engineer/Fechii-Application-Chemical-Engineer/
         git push origin master
        
         echo "checking the artifacts..."
         cd /home/runner/work/Fechii-Application-Chemical-Engineer/output/
         ls
         pwd
         
    - uses: actions/upload-artifact@v2
      with:
        name: output results
        path: /home/runner/work/Fechii-Application-Chemical-Engineer/output/ 
